typedef char int8;
typedef unsigned char uint8;
typedef short int16;
typedef unsigned short uint16;
typedef int int32;
typedef unsigned int uint32;
typedef long long int64;
typedef unsigned long long uint64;
typedef __int128 int128;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef float float32;
typedef double float64;
